import "./globals.css";
import { yekan } from "@/utils/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${yekan.className} max-w-6xl mx-auto`}>{children}</body>
    </html>
  );
}
